CREATE DATABASE SALES_DB;


USE SALES_DB;
CREATE TABLE CUSTOMERS(
	CUSTOMER_ID INT UNIQUE NOT NULL
PRIMARY KEY,
	NAME VARCHAR (255) NOT NULL,
    PHONE_NO VARCHAR(15) NOT NULL,
    EMAIL CHAR(255) UNIQUE,
    ADDRESS CHAR (255)NOT NULL,
    GENDER ENUM('MALE','FEMALE','OTHERS')
);


USE PRACTISE;
DROP TABLE CUSTOMERS;

USE SALES_DB;
-- PRODUCTS TABLE
-- COLUMNS: PRODUCT_ID, PRODUCT_NAME, DESCRIPTION, CATEGORY, SERIAL_NO

CREATE TABLE PRODUCTS(
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME CHAR(255) NOT NULL,
    DESCRIPTION CHAR(255) NOT NULL,
    CATEGORY CHAR(255) NOT NULL DEFAULT('TECHNOLOGY'),
    SERIAL_NO INT NOT NULL
    );
    
    SELECT * FROM PRODUCTS;
    
-- ORDERS TABLE
-- COLUMNS: ORDER_ID, ORDER_DATE, PRICE, QUANTITY, CUSTOMER_ID, PRODUCT_ID

CREATE TABLE ORDERS(
    ORDER_ID INT PRIMARY KEY,
    ORDER_DATE DATE,
    PRICE INT NOT NULL,
    QUANTITY INT NOT NULL,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
    );
    

SELECT * FROM CUSTOMERS;

INSERT INTO CUSTOMERS(CUSTOMER_ID, NAME, PHONE_NO, EMAIL, ADDRESS, GENDER)
VALUES(1, "OLA", "803237777", "OLA@YAHOO.COM", "20 AWOLOWO WAY", "MALE");

-- INSERT MULTIPLE VALUES
INSERT INTO CUSTOMERS()
VALUES(2, "JOY", "0902348768", "JOY_g@GMAIL.COM", "1 OBA CLOSE", "FEMALE"),
(3, "TOLA", "091234567", "TOLA@YAHOO.COM", "15 OBA AKRAN IKEJA", "FEMALE"),
(4, "BOLA", "+4490010203", "BOLA@YAHOO.COM", "12 LONDON AV", "FEMALE");

SELECT * FROM CUSTOMERS;

-- INSERT INTO PRODUCTS TABLE
INSERT INTO PRODUCTS()
VALUES(1, "MICROWAVE", "1500 WATT MICROWAVE", "HOME APPLIANCES", 1001),
(2, "TELEVISION", "49 INCHES OLED TV", "ELECTRONICS", 1002),
(3, "DANO MILK", "WHOLE MILK", "GROCERIES", 1003),
(4, "SOUND BAR", "1500 WATT SAMSUNG SOUND BAR", DEFAULT, 1004);

SELECT * FROM PRODUCTS;

SELECT * FROM ORDERS;
-- INSERT DATA INTO ORDERS TABLE
INSERT INTO ORDERS()
VALUES(1, current_date(), 300000, 1, 3, 2),
(2, current_date(), 45000, 4, 1, 4);

SELECT * FROM ORDERS;

-- CHECKING THE FOREIGN KEY CONSTRAINT
INSERT INTO ORDERS()
VALUES(3, current_date(), 120000,2,8,1);

SELECT * FROM crude